name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18' # You can specify your Node.js version here

      - name: Install dependencies
        run: npm install

      - name: Diagnose Vite executable
        run: |
          ls -l node_modules/.bin/vite
          file node_modules/.bin/vite
          ls -l node_modules/.bin/

      - name: Grant execute permission to Vite
        run: chmod +x node_modules/.bin/vite

      - name: Build
        run: npm run build

      - name: Deploy to GitHub Pages
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git checkout main
          git add dist -f
          git commit -m "Deploy to GitHub Pages" || true
          git subtree push --prefix dist origin main
